# Generated by Django 2.2.1 on 2019-06-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='list_id',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='user_id',
            new_name='user',
        ),
    ]
